describe('Registration Func', () => {
    it('Register new user', () => {
        cy.visit('https://parabank.parasoft.com/parabank/index.htm')
        cy.get('#loginPanel > :nth-child(3) > a').click()
        cy.get("input[name='customer.firstName']").type('Rizz')
        cy.get("input[name='customer.lastName']").type('-33')
        cy.get("input[name='customer.address.street']").type('34983, Colombo')
        cy.get("input[name='customer.address.city']").type('Colombo')
        cy.get("input[name='customer.address.state']").type('Western')
        cy.get("input[name='customer.address.zipCode']").type('98328')
        cy.get("input[name='customer.phoneNumber']").type('123456789')
        cy.get("input[name='customer.ssn']").type('23287329478724')
        cy.get("input[name='customer.username']").type('Rizz-33')
        cy.get("input[name='customer.password']").type('Rizz')
        cy.get("input[name='repeatedPassword']").type('Rizz')
        cy.get('[colspan="2"] > .button').click()
    })
})